import tkinter as tk
from tkinter import ttk

class EstimateStay(tk.Frame):
  def __init__(self, master):
    super().__init__(master)
    self.pack()
    
    master.state('zoomed')
    master.geometry('420x550')
    master.title('見積もり画面（宿泊）')

    self.create_widgets()

  # ウィジェットを配置して画面作るメソッド
  def create_widgets(self):
      tk.Label(self, text='').grid(row=0, column=0, padx=10, pady=5)
      tk.Label(self, text='宿泊').grid(row=1, column=0, padx=10, pady=5)
      ttk.Separator(self, orient='vertical').grid(row=1, column=1, rowspan=18, sticky='ns', padx=5)
      
      tk.Label(self, text='単価（八幡平豚）').grid(row=1, column=2, padx=10, pady=5)
      tk.Label(self, text='単価（岩手県産牛）').grid(row=1, column=3, padx=10, pady=5)
      tk.Label(self, text='単価（前沢牛）').grid(row=1, column=4, padx=10, pady=5)
      tk.Label(self, text='注文数').grid(row=1, column=5, padx=10, pady=5)
      tk.Label(self, text='合計').grid(row=1, column=6, padx=10, pady=5)
      ttk.Separator(self, orient='vertical').grid(row=1, column=7, rowspan=18, sticky='ns', padx=5)
      tk.Label(self, text='宿泊').grid(row=1, column=8, padx=10, pady=5)
      ttk.Separator(self, orient='vertical').grid(row=1, column=9, rowspan=18, sticky='ns', padx=5)
      tk.Label(self, text='単価').grid(row=1, column=10, padx=10, pady=5)
      tk.Label(self, text='注文数').grid(row=1, column=11, padx=10, pady=5)
      tk.Label(self, text='合計').grid(row=1, column=12, padx=10, pady=5)
      
      ttk.Separator(self, orient='horizontal').grid(row=2, column=0, columnspan=14, sticky='ew', pady=5)
      
      tk.Label(self, text='1F和室(本館和室7.5畳)　大人').grid(row=3, column=0, padx=10, pady=5)
      tk.Label(self, text='1F和室(本館和室7.5畳)　子供').grid(row=4, column=0, padx=10, pady=5)
      tk.Label(self, text='1F西館洋室　大人').grid(row=5, column=0, padx=10, pady=5)
      tk.Label(self, text='1F西館洋室　子供').grid(row=6, column=0, padx=10, pady=5)
      tk.Label(self, text='岩手山側和室　大人').grid(row=7, column=0, padx=10, pady=5)
      tk.Label(self, text='岩手山側和室　子供').grid(row=8, column=0, padx=10, pady=5)
      tk.Label(self, text='岩手山側露天風呂付き和室　大人').grid(row=9, column=0, padx=10, pady=5)
      tk.Label(self, text='岩手山側露天風呂付き和室　子供').grid(row=10, column=0, padx=10, pady=5)
      tk.Label(self, text='西館和室10畳　大人').grid(row=11, column=0, padx=10, pady=5)
      tk.Label(self, text='西館和室10畳　子供').grid(row=12, column=0, padx=10, pady=5)
      tk.Label(self, text='1F檜内風呂付き和洋室　大人').grid(row=13, column=0, padx=10, pady=5)
      tk.Label(self, text='1F檜内風呂付き和洋室　子供').grid(row=14, column=0, padx=10, pady=5)
      tk.Label(self, text='1F西館和洋室　大人').grid(row=15, column=0, padx=10, pady=5)
      tk.Label(self, text='1F西館和洋室　子供').grid(row=16, column=0, padx=10, pady=5)
      tk.Label(self, text='西館和室28畳　大人').grid(row=17, column=0, padx=10, pady=5)
      tk.Label(self, text='西館和室28畳　子供').grid(row=18, column=0, padx=10, pady=5)
      tk.Label(self, text='ドックワン　宿泊').grid(row=3, column=8, padx=10, pady=5)
      tk.Label(self, text='ドックワン　スパ').grid(row=4, column=8, padx=10, pady=5)
      tk.Label(self, text='岩盤浴').grid(row=5, column=8, padx=10, pady=5)
      tk.Label(self, text='パークゴルフ　大人').grid(row=6, column=8, padx=10, pady=5)
      tk.Label(self, text='パークゴルフ　子供').grid(row=7, column=8, padx=10, pady=5)
      tk.Label(self, text='パターゴルフ　大人').grid(row=8, column=8, padx=10, pady=5)
      tk.Label(self, text='パターゴルフ　子供').grid(row=9, column=8, padx=10, pady=5)
      tk.Label(self, text='テニスコート　宿泊者').grid(row=10, column=8, padx=10, pady=5)
      tk.Label(self, text='テニスコート　外来').grid(row=11, column=8, padx=10, pady=5)
      tk.Label(self, text='テニスコート　延長').grid(row=12, column=8, padx=10, pady=5)
      tk.Label(self, text='テニスコート　ボール').grid(row=13, column=8, padx=10, pady=5)
      tk.Label(self, text='温泉貸し切り').grid(row=14, column=8, padx=10, pady=5)
      
      tk.Label(self, text='12400').grid(row=3, column=2, padx=10, pady=5)
      tk.Label(self, text='').grid(row=4, column=2, padx=10, pady=5)
      tk.Label(self, text='12400').grid(row=5, column=2, padx=10, pady=5)
      tk.Label(self, text='').grid(row=6, column=2, padx=10, pady=5)
      tk.Label(self, text='12400').grid(row=7, column=2, padx=10, pady=5)
      tk.Label(self, text='7200').grid(row=8, column=2, padx=10, pady=5)
      tk.Label(self, text='14400').grid(row=9, column=2, padx=10, pady=5)
      tk.Label(self, text='7200').grid(row=10, column=2, padx=10, pady=5)
      tk.Label(self, text='12400').grid(row=11, column=2, padx=10, pady=5)
      tk.Label(self, text='7200').grid(row=12, column=2, padx=10, pady=5)
      tk.Label(self, text='15400').grid(row=13, column=2, padx=10, pady=5)
      tk.Label(self, text='7200').grid(row=14, column=2, padx=10, pady=5)
      tk.Label(self, text='12400').grid(row=15, column=2, padx=10, pady=5)
      tk.Label(self, text='7200').grid(row=16, column=2, padx=10, pady=5)
      tk.Label(self, text='12400').grid(row=17, column=2, padx=10, pady=5)
      tk.Label(self, text='7200').grid(row=18, column=2, padx=10, pady=5)
      
      tk.Label(self, text='15400').grid(row=3, column=3, padx=10, pady=5)
      tk.Label(self, text='').grid(row=4, column=3, padx=10, pady=5)
      tk.Label(self, text='15400').grid(row=5, column=3, padx=10, pady=5)
      tk.Label(self, text='').grid(row=6, column=3, padx=10, pady=5)
      tk.Label(self, text='15400').grid(row=7, column=3, padx=10, pady=5)
      tk.Label(self, text='7200').grid(row=8, column=3, padx=10, pady=5)
      tk.Label(self, text='17400').grid(row=9, column=3, padx=10, pady=5)
      tk.Label(self, text='7200').grid(row=10, column=3, padx=10, pady=5)
      tk.Label(self, text='15400').grid(row=11, column=3, padx=10, pady=5)
      tk.Label(self, text='7200').grid(row=12, column=3, padx=10, pady=5)
      tk.Label(self, text='18400').grid(row=13, column=3, padx=10, pady=5)
      tk.Label(self, text='7200').grid(row=14, column=3, padx=10, pady=5)
      tk.Label(self, text='15400').grid(row=15, column=3, padx=10, pady=5)
      tk.Label(self, text='7200').grid(row=16, column=3, padx=10, pady=5)
      tk.Label(self, text='15400').grid(row=17, column=3, padx=10, pady=5)
      tk.Label(self, text='7200').grid(row=18, column=3, padx=10, pady=5)
      
      tk.Label(self, text='18400').grid(row=3, column=4, padx=10, pady=5)
      tk.Label(self, text='').grid(row=4, column=4, padx=10, pady=5)
      tk.Label(self, text='18400').grid(row=5, column=4, padx=10, pady=5)
      tk.Label(self, text='').grid(row=6, column=4, padx=10, pady=5)
      tk.Label(self, text='18400').grid(row=7, column=4, padx=10, pady=5)
      tk.Label(self, text='7200').grid(row=8, column=4, padx=10, pady=5)
      tk.Label(self, text='20400').grid(row=9, column=4, padx=10, pady=5)
      tk.Label(self, text='7200').grid(row=10, column=4, padx=10, pady=5)
      tk.Label(self, text='18400').grid(row=11, column=4, padx=10, pady=5)
      tk.Label(self, text='7200').grid(row=12, column=4, padx=10, pady=5)
      tk.Label(self, text='20400').grid(row=13, column=4, padx=10, pady=5)
      tk.Label(self, text='7200').grid(row=14, column=4, padx=10, pady=5)
      tk.Label(self, text='18400').grid(row=15, column=4, padx=10, pady=5)
      tk.Label(self, text='7200').grid(row=16, column=4, padx=10, pady=5)
      tk.Label(self, text='18400').grid(row=17, column=4, padx=10, pady=5)
      tk.Label(self, text='7200').grid(row=18, column=4, padx=10, pady=5)
      
      tk.Label(self, text='1000').grid(row=3, column=10, padx=10, pady=5)
      tk.Label(self, text='1800(二頭目以降1000増)').grid(row=4, column=10, padx=10, pady=5)
      tk.Label(self, text='1500').grid(row=5, column=10, padx=10, pady=5)
      tk.Label(self, text='600').grid(row=6, column=10, padx=10, pady=5)
      tk.Label(self, text='300').grid(row=7, column=10, padx=10, pady=5)
      tk.Label(self, text='500').grid(row=8, column=10, padx=10, pady=5)
      tk.Label(self, text='250').grid(row=9, column=10, padx=10, pady=5)
      tk.Label(self, text='1000').grid(row=10, column=10, padx=10, pady=5)
      tk.Label(self, text='1500').grid(row=11, column=10, padx=10, pady=5)
      tk.Label(self, text='1000').grid(row=12, column=10, padx=10, pady=5)
      tk.Label(self, text='300').grid(row=13, column=10, padx=10, pady=5)
      tk.Label(self, text='2500').grid(row=14, column=10, padx=10, pady=5)

      
      tk.Label(self, text='').grid(row=19, column=0, padx=10, pady=5)
      tk.Label(self, text='合計料金').grid(row=20, column=0, padx=10, pady=5)
      
      self.mail_btn = tk.Button(self, text='メール送信')
      self.mail_btn.grid(row=20, column=3, padx=10, pady=5)
      self.jason_btn = tk.Button(self, text='ジェイソンファイル保存')
      self.jason_btn.grid(row=20, column=4, padx=10, pady=5)
      
if __name__ == '__main__':
  root = tk.Tk()
  app = EstimateStay(root)
  app.mainloop()
